### ISSUE TITLE
Odbc connection issues

### ISSUE THREAD

**Issue by PingLord** [MariaDB/mariadb-connector-odbc#1]
Environment : 

Ms Access DB 2013 linked to MariaDb server using MariaDb ODBC .

I have installed the MariaDB ODBC and everything worked perfect, "Test DSN" returns the "Connection succesfully established " message but in MS Access when i try to link to the MariaDB ODBC , i get "ODBC -- call failed (0*) , invalid information type (#0)" error message.

If im using the Mysql ODBC for the MariaDB server i get a malformed response , which is a usual response when a Mysql Table does not have a unique index.I have confirmed the table does have primary index,it is auto increment.

Another thing i observed is that every time i open the ODBC configuration,the "How do you want co connect to MariaDB" radio buttons are unselected,however,the "Test DSN" returns the "Connection succesfully established" message.

I have attached also a printscreen of the error message.
![issue_mariadb07](https://cloud.githubusercontent.com/assets/5277240/7269777/7ca9cb50-e8df-11e4-98e3-3da8117e7134.PNG)

**Comment by lawrinn** [comment]
This issue has been fixed in the 1.0.5 release
