### ISSUE TITLE
Tag 3.0.0 shouldn't exist as such?

### ISSUE THREAD

**Issue by mika** [MariaDB/mariadb-connector-odbc#16]
https://github.com/MariaDB/mariadb-connector-odbc/releases/tag/3.0.0 is considered newer than the latest actual release/tag 2.0.15, could this 3.0.0 tag please removed therefore? (This is causing troubles e.g. with automatic version identification like in https://wiki.debian.org/debian/watch)

Thanks!

**Comment by AdamMajer** [comment]
You need to report this on JIRA because apparently no one reads issues here *and* no one bothered to turn off issues tracker on GitHub for this project.

**Comment by mika** [comment]
Sigh :-/ Thanks for the info @AdamMajer 

Nowadays v3.0.2 and its tag exists, so the 3.0.0 issue no longer exists as such even though the tag is still there, so I didn't bother moving this towards JIRA.
