### ISSUE TITLE
Error Compiling mariadb-connector-odbc:  MariaDB not found

### ISSUE THREAD

**Issue by DavisSylvester** [MariaDB/mariadb-connector-odbc#2]
I am getting the following error when compiling MariaDB Connection on Linux:

-- Found MariaDB includes: /usr/local/include
CMake Error at CMakeLists.txt:110 (MESSAGE):
  **MariaDB not found**

-- Configuring incomplete, errors occurred!
See also "/downloads/mariadb-connector-odbc/CMakeFiles/CMakeOutput.log".
See also "/downloads/mariadb-connector-odbc/CMakeFiles/CMakeError.log".

I am trying to get MariaDB Connector to work with UnixODBC.

Using MariaDB Server:  **Server version: 10.1.7-MariaDB Source distribution**

I am using mariadb-connector-odbc v.1.0.5 and have also tried in 1.0.6.  Same Error on both.

**Comment by driesken** [comment]
Have you found a solution for this? I'm having the same issue.

**Comment by lawrinn** [comment]
Hi,

On 17.10.2015 18:56, Davis Sylvester wrote:
>
> I am getting the following error when compiling MariaDB Connection on 
> Linux:
>
> -- Found MariaDB includes: /usr/local/include
> CMake Error at CMakeLists.txt:110 (MESSAGE):
> MariaDB not found
>
> -- Configuring incomplete, errors occurred!
> See also "/downloads/mariadb-connector-odbc/CMakeFiles/CMakeOutput.log".
> See also "/downloads/mariadb-connector-odbc/CMakeFiles/CMakeError.log".
>
> I am trying to get MariaDB Connector to work with UnixODBC.
>
> Using MariaDB Server: *Server version: 10.1.7-MariaDB Source distribution*
>
> I am using mariadb-connector-odbc v.1.0.5 and have also tried in 
> 1.0.6. Same Error on both.
>

There are few things here.
First - you need to use odbc-2.0 branch of c/odbc. 1.0.x is windows only 
connector.
Then, c/odbc relies on some features available only in MariaDb 
Connector/C.  So, you need that to to build driver on *nix. And I think 
the last released 2.2 C/C won't fit - you need take 2.2 branch from 
github(master branch will probably do to).

If cmake cannot find MariaDB, you can point to it in MARIADB_DIR env 
variable. Or you can supply 
-DMARIADB_BIN_DIR=/path/dir_with_mariadb_config in cmake command line 
parameters. Or you can even directly supply to cmake MARIADB_INCLUDE_DIR 
and MARIADB_LIBRARY_DIR values in similar manner. And you don'tneed to 
do all of this if your mariadb c/c files are in standard places, i.e. 
you did make install after c/c build. cmake is supposed to find them then

Then you will need UnixODBC. iODBC is not supported so far(and we don't 
have particular plans re it yet). We use latest 2.3 releases internally. 
I guess all 2.3 should be fine. Not sure if it will work with older 
versions, possibly not.

And the last thing - we are currently building public c/odbc 2.0 
release. You can wait for it, I guess it will make your life a bit easier.

Best regards,
Lawrin

**Comment by DavisSylvester** [comment]
No, I never got it to work.  I am going to try to use the MySQL connector instead.

**Comment by driesken** [comment]
Thanks Lawrin, I'll wait for the c/odbc 2.0 release then.

For now I'll stick to mysql-connector-odbc.

**Comment by DavisSylvester** [comment]
No, I never got it to work.  I am going to try to use the MySQL 
connector instead.

**Comment by powerpbx** [comment]
Anyone have a solution to this yet?  The 2.0.9 binary won't work on CentOS v7

**Comment by lawrinn** [comment]
For 2.0.10  Centos7 binaries has been published

**Comment by powerpbx** [comment]
Unfortunately 2.0.10 crashes Centos 7 for me.  Unless I am doing something wrong.

My /etc/odbcinst.ini is as follows:
`[MySQL]
Description	= ODBC for MySQL
# Driver		= /usr/lib/libmyodbc5.so
# Driver		= /usr/lib/libmaodbc.so
# Setup		= /usr/lib/libodbcmyS.so
# Driver64	= /usr/lib64/libmyodbc5.so
Driver64	= /usr/lib64/libmaodbc.so
Setup64		= /usr/lib64/libodbcmyS.so
FileUsage	= 1`

**Comment by powerpbx** [comment]
I should clarify.  MariaDB ODBC v2.0.10 CenOS v7 binary crashes my application when maradb v10.1.14 is running with Galera Cluster is enabled.  It does not crash when it is running in standalone mode.

**Comment by nirbhayc** [comment]
@powerpbx The crash could be related to Galera server and not connector. Could you share the stack trace from server's error log?

**Comment by powerpbx** [comment]
If I remove the mariadb odbc file it does not crash.  I just can't use odbc.

**Comment by lawrinn** [comment]
@powerpbx, could you please provide unixOdbc trace for the crash? and perhaps it's better to file the bug for it on http://jira.mariadb.org/

**Comment by powerpbx** [comment]
It was a configuration issue on the app.  Sorry for the false alarm.
