### ISSUE TITLE
Newlines at start of query will return closed / empty recordset

### ISSUE THREAD

**Issue by adzm** [MariaDB/mariadb-connector-odbc#3]
If you execute something like "
SELECT 1" you will get a closed recordset in response. Of course "SELECT 1" works fine. Perhaps leading whitespace just needs to be trimmed.

**Comment by lawrinn** [comment]
Thank you for the report. Did you check on current repository version? or on the last release? I guess I fixed this already.

**Comment by adzm** [comment]
It turns out to only be a problem when the statement is not terminated with a semicolon! I was using the latest stable release, though I'll build master soon and give it a shot.

**Comment by lawrinn** [comment]
Semicolon is not required for single statement. and even shouldn't be there.
And I appreciate your help with checking this

**Comment by adzm** [comment]
Same results with a comment at the beginning, or a tab + space. Unless there is a semicolon, no results returned. I have not tried the 2.0 era versions since they appear to be linux only. I am using this on a Windows environment at work, and I have already built and run MariaDB, but having trouble getting cmake and everything working for this project, unfortunately.

**Comment by lawrinn** [comment]
I could not repeat it in both branches we currently have.
The issue looks pretty much as one of problems here https://jira.mariadb.org/browse/ODBC-29 , and that has been fixed. I added the testcase to the testsuite, and I am closing the issue for now. Re-opening is always the option :)
