### ISSUE TITLE
[ASK]defferent odbc MariaDB and Mysql using foxpro

### ISSUE THREAD

**Issue by atmanegara** [MariaDB/mariadb-connector-odbc#4]
1. ![13102889_10206320478791745_1986593470296680775_n](https://cloud.githubusercontent.com/assets/9096711/14875001/bb66d3fa-0d38-11e6-9d82-696e1e3b1b3e.jpg)
2. ![2](https://cloud.githubusercontent.com/assets/9096711/14875007/bf7ae3e6-0d38-11e6-8640-85f5334e2341.PNG)

[error]
![1](https://cloud.githubusercontent.com/assets/9096711/14876112/3154ed9e-0d44-11e6-88d2-f6947211512d.PNG)

why result odbc mariaDB (img no 1) and Mysql ((img no 2) different?, but 2 odbc succes insert to tabel using same sintax
i'm using visual foxpro 

*Sorry for my bad English ,  i'm from indonesia

**Comment by lawrinn** [comment]
Do you mean that that with MariaDB connector the row is not really inserted? Or it is not displayed? Can you verify that?
Also, it is not quite clear where and when "out of sync" error occurs? Can you provide small testcase here?

**Comment by atmanegara** [comment]
first, i'm test in my foxpro
![1](https://cloud.githubusercontent.com/assets/9096711/14882859/82f30662-0d6d-11e6-95b3-1b8128a23f9d.PNG)

line black > driver mariaDB, line blue sintax sql  to passing using Sqlexec (line red) then result of sqlexec is 1 ,it is mean success but -1 is invalid,

then, test again 
![2](https://cloud.githubusercontent.com/assets/9096711/14883058/a58e34fc-0d6e-11e6-8319-d79bd1acd328.PNG)
look message of result sqlexec is -1 , it is mean invalid but in table success insert, deffirent using Odbc Mysql,
![2](https://cloud.githubusercontent.com/assets/9096711/14883299/196ab002-0d70-11e6-91e6-2409d6eb9d30.PNG)
result sqlexec is 1, cz is my problem if using odbc mariaDb

**Comment by lawrinn** [comment]
I have created the issue for this in MariaDB jira https://jira.mariadb.org/browse/ODBC-41
Closing the issue here
