### ISSUE TITLE
"fatal error: my_global.h: No such file or directory" when building from source

### ISSUE THREAD

**Issue by rhansen** [MariaDB/mariadb-connector-odbc#6]
I get the following when I try to build the odbc-2.0 branch (rev fbd517e):

```
$ cd ~/mariadb-connector-odbc
$ git clean -dxf && mkdir _build && (cd _build && cmake .. && make)
-- The C compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for floor
-- Looking for floor - not found
-- Looking for floor in m
-- Looking for floor in m - found
-- Found MariaDB libraries: /usr/local/lib/mariadb
-- Found ODBC Driver Manager includes: /usr/include
-- Found ODBC Driver Manager libraries: /usr/lib/x86_64-linux-gnu
-- Checking if SQLColAttribute expects SQLPOINTER FALSE
-- Configuring to build without SSL support
-- Configuring tests for linking against the DM library
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Success
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so
-- License File: /home/rhansen/mariadb-connector-odbc/COPYING
-- ReadMe File: /home/rhansen/mariadb-connector-odbc/README
-- Source Package Filename: mariadb-connector-odbc-2.0.11-ga-src.TGZ
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rhansen/mariadb-connector-odbc/_build
Scanning dependencies of target maodbc
[  1%] Building C object CMakeFiles/maodbc.dir/odbc_3_api.c.o
In file included from /home/rhansen/mariadb-connector-odbc/odbc_3_api.c:21:0:
/home/rhansen/mariadb-connector-odbc/ma_odbc.h:32:23: fatal error: my_global.h: No such file or directory
compilation terminated.
CMakeFiles/maodbc.dir/build.make:62: recipe for target 'CMakeFiles/maodbc.dir/odbc_3_api.c.o' failed
make[2]: *** [CMakeFiles/maodbc.dir/odbc_3_api.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/maodbc.dir/all' failed
make[1]: *** [CMakeFiles/maodbc.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Versions:
  * Ubuntu 16.04 (Xenial) 64-bit
  * mariadb-connector-c built from source (master branch rev 437b9cd) and installed to /usr/local
  * libmariadbclient-dev 10.1.14+maria-1~xenial package from one of the mirrors listed in https://downloads.mariadb.org/mariadb/repositories/
  * unixodbc-dev 2.3.1-4.1 package

**Comment by lawrinn** [comment]
I made a copy of the report here https://jira.mariadb.org/browse/ODBC-40, and closing your issue here.

It's a bit strange that cmake doesn't say, that it found includes, but says, that it found libraries. Should be only if includes had been found.

**Comment by artemklevtsov** [comment]
Any updates for this issue?

**Comment by lawrinn** [comment]
Basically the issue here is that wrong version of C/C is used. To build C/ODBC 2.0 one needs C/C v.2.3, and that must be C/C 3.0.x that the reporter had. Since 3.0 does not have my_global.h file any more.
The bug here is that cmake does not detect if the C/C version is suitable for the build

**Comment by artemklevtsov** [comment]
Thank you for the reply. Sorry for the offtop.
I built mariadb-connector-c 3.0.2-1 and try mariadb-connector-odbc 3.0.1. Now faild with:
> ma_odbc.h:361:3: error: unknown type name 'MARIADB_CHARSET_INFO

**Comment by lawrinn** [comment]
On 18.08.2017 14:33, Artem Klevtsov wrote:
>
> Thank you for the reply. Sorry for the offtop.
> I built mariadb-connector-c 3.0.2-1 and try mariadb-connector-odbc 
> 3.0.1. Now faild with:
>
>     ma_odbc.h:361:3: error: unknown type name 'MARIADB_CHARSET_INFO
>

Well, I wouldn't call this offtop, really.

Don't you have some other headers it picks instead of headers from 
3.0.2? Because c/c 3.0.2 has that struct type definition.
Look at cmake output or grep MARIADB_INCLUDE_DIR CMakeCache.txt what is used

**Comment by artemklevtsov** [comment]
Thank for the replies. Fixed with the correct `MARIADB_INCLUDE_DIR`.
