### ISSUE TITLE
MARIADB-CONNECTOR-ODBC gives syntax errors when I invoke make

### ISSUE THREAD

**Issue by mikewardmckee** [MariaDB/mariadb-connector-odbc#7]
I do the following:

1, built MARIADB Server (10.1) on Ubuntu Successfully
2. Get Syntax error on ma_helper.c when it refers to line 433. It says it doesn't have a member named char_maxlen for CHARSET_INFO. I noticed that the mysql header file that defines CHARSET_INFO is called m_ctype.h. For CHARSET_INFO it does not have that member. What am I doing wrong?

**Comment by lawrinn** [comment]
To build Connector/ODBC you need Connector/C, and not headers and client library from the server.
Currently C/ODBC uses latest Connnector/C from 2.2 series(connector_c_2.2 branch on github)

**Comment by lawrinn** [comment]
Closing for now. There is one more build issue anyway

**Comment by lawrinn** [comment]
After some thinking - there is a bug here. cmake should not pick headers from server. I won't re-open this issue, I have https://jira.mariadb.org/browse/ODBC-39 for it open

**Comment by mikewardmckee** [comment]
How do you currently build it?, as I get errors on both Windows and Linux when they attempt to include my_global.h (which is a mysql include file) or getopt.h (which is also mysql). It seems like those header files are necessary, but when I include them, I get different compile errors when I attempt to build ODBC. The Connector/C works fine, but what include file directories do you include to get the ODBC to work.

**Comment by mikewardmckee** [comment]
I figured out my mistake. I was using master version instead of the ones
required for UNIX.

Thanks
